name: Compile

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile resource files
        run: |
          compile-tsr.bat
      - name: Upload compiled DLLs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TSR_DLLs
          path: |
            output/EXE/*.dll
